changes in numpy


In [3]:
a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [2]:
import numpy as np

In [5]:
# get specifiuc elements

a[0, 5]

6

In [6]:
# get a row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
# get column
a[:, 2]

array([ 3, 10])

In [12]:
# startindex endindex
a[0, 1:-1:2]

array([2, 4, 6])

In [15]:
a[1,5] = 20
print (a)

a[:,2] = [1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [17]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
# get a specific area
b[0,0,1]

2

In [26]:
# replace
b[:,1,:] = [[9,9],[5,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [5 8]]]


initiallizing different type of methods


In [31]:
#all 0s matrix
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
# all 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [35]:
# any other number
np.full((3,3), 7, dtype='float32')

array([[7., 7., 7.],
       [7., 7., 7.],
       [7., 7., 7.]], dtype=float32)

In [37]:
# any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [41]:
# ransom decimal numbers
np.random.rand(4,2,3)
#np.random.random_sample(a.shape)

array([[[0.98568199, 0.73764472, 0.94367858],
        [0.96262581, 0.48472668, 0.82518865]],

       [[0.88377236, 0.33579331, 0.08360204],
        [0.42938228, 0.80622412, 0.75595579]],

       [[0.96675562, 0.26362109, 0.24787711],
        [0.25503903, 0.23894168, 0.96993862]],

       [[0.78084735, 0.01279097, 0.12251499],
        [0.56033414, 0.15106526, 0.95181322]]])

In [44]:
# random integer value
np.random.randint(4,8, size=(3,3))

array([[6, 5, 7],
       [4, 4, 4],
       [4, 7, 4]])

In [46]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [53]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [55]:
mat = np.ones((5,5))
print(mat)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [64]:
z = np.zeros((3,3))
z[1,1]=9
#print(z)

mat[1:4,1:4] = z
print(mat)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [70]:
# be careful when copy
a = np.array([1,2])
b = a.copy()
b[0]=100
print(a)
print(b)

[1 2]
[100   2]


In [3]:
# mathemetics

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
a + 2

array([3, 4, 5, 6])

In [5]:
a - 2

array([-1,  0,  1,  2])

In [7]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [8]:
a * 2

array([2, 4, 6, 8])

In [9]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [10]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [13]:
# take the sin
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [14]:
# Linear alegebra


In [18]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [20]:
# determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [21]:
# statistics
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np.min(stats, axis = 0)

array([1, 2, 3])

In [23]:
np.max(stats)

6

In [26]:
np.sum(stats, axis = 0)

array([5, 7, 9])

## reorganizing aarays

In [33]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [36]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
# horizontal stacks
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# mischellaneous

### load data from file

In [56]:
filedata = np.genfromtxt("abc.txt", delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,   2,   3,   4,   5,   6,   7,   8, 956,   4],
       [ 12, 435,  46,  67,   5, 344,  53,  56,   7, 678]])

## boolean masking and advance indexing

In [60]:
filedata[filedata>50]

array([956, 435,  67, 344,  53,  56, 678])

In [61]:
# index with list in numpy
a  = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [62]:
np.all(filedata > 50, axis=0)

array([False, False, False, False, False, False, False, False, False,
       False])

In [63]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False,  True, False, False,  True,  True, False,
        False]])